version: '3.7'

services:
  notebook:
    build: .
    working_dir: /work
    volumes:
      - .:/work
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    command: [ "/bin/bash", "docker_cmd.sh" ]
    environment:
      PYTHONPATH: /work:/work
    env_file:
      - .env
    ports:
      - 8888:8888 # web
